### ISSUE TITLE
Github Authentication

### ISSUE THREAD

**Issue by Jeeiii** [quadratic-funding/qfi#49]
In order to authenticate users through Github OAuth and then authorize them on Firebase using a NodeJS CLI tool, we need to handle the [Device Authorization Flow](https://firebase.google.com/docs/auth/web/github-auth) manually.

Other resources:
- Github Docs: [Device Flow](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#device-flow)

**TODOs**
- Device Authorization Flow 
   - [x] Create and authorize an OAuth Github application
   - [x] Firebase Authorization w/ OAuth Github configuration
   - [x] Simple CLI Device Flow implementation
   - [x] Exchange the Github OAuth 2.0 access token for a Firebase credential 

- CLI
    - [x] Design a minimal interactive Github OAuth Device Flow
    - [x] Develop the features listed below.

- __Features__
   - Timeout for Github OAuth code.
   - Interactive menus.
   - Explanations for each step.
   - Flexible lib/ utilities/helpers.
   - Logs in automatically if the token is saved locally after the first login.
   - Give users support when errors occur.
   - Theming.
   - Firebase Services bootstrap.
